services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: omniquery_postgres
    restart: always
    environment:
      POSTGRES_USER: omni_user
      POSTGRES_PASSWORD: omni_password
      POSTGRES_DB: omniquery_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
